// Writes src/content/icon-nodes.ts: the SVG nodes of the 14 module icons, copied from lucide-react (ISC licence),
// so ModuleIcon can render plain <svg> on the server and lucide's client-only Icon component never ships to the browser.
// Re-run after changing the icon list: node scripts/gen-icons.mjs
import { writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";

const ICONS = {
  ReceiptText: "receipt-text", HeartHandshake: "heart-handshake", ShoppingCart: "shopping-cart", Package: "package", Factory: "factory",
  Scale: "scale", Landmark: "landmark", FileText: "file-text", ChartColumn: "chart-column", SlidersHorizontal: "sliders-horizontal",
  Hammer: "hammer", FlaskConical: "flask-conical", ScanLine: "scan-line", LockKeyhole: "lock-keyhole",
};
const out = {};
for (const [name, file] of Object.entries(ICONS)) {
  const m = await import(pathToFileURL(resolve(`node_modules/lucide-react/dist/esm/icons/${file}.mjs`)).href);
  out[name] = m.__iconData.node.map(([tag, attrs]) => [tag, Object.fromEntries(Object.entries(attrs).filter(([k]) => k !== "key"))]);
}
writeFileSync(
  "src/content/icon-nodes.ts",
  `// Generated by scripts/gen-icons.mjs from lucide-react (ISC licence). Do not edit.\nexport type IconNode = [string, Record<string, string>][];\nexport const ICON_NODES: Record<string, IconNode> = ${JSON.stringify(out)};\n`,
);
console.log("icon-nodes.ts written");
